global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metrics_path: "/admin/metrics"
    params:
      format: ["prometheus"]
